/**
 * Code Log Component
 *
 * Accumulates Python code snippets generated by API calls and displays
 * them in a compact, scrollable log.  Users can copy individual snippets,
 * clear the log, or download the full session as a `.py` file.
 *
 * Integration:
 *  - Listen for `code-log-entry` CustomEvents on `document`.
 *    Each event's `detail` should be `{ label: string, code: string }`.
 *  - Or call `addEntry(label, code)` programmatically.
 *
 * Usage:
 *   <code-log></code-log>
 */

import { escapeHtml } from '../iri/uri-utils';

interface LogEntry {
  label: string;
  code: string;
  timestamp: Date;
}

export class CodeLog extends HTMLElement {
  private root: ShadowRoot;
  private entries: LogEntry[] = [];

  constructor() {
    super();
    this.root = this.attachShadow({ mode: 'open' });
  }

  connectedCallback(): void {
    this.render();
    document.addEventListener('code-log-entry', ((e: CustomEvent) => {
      const { label, code } = e.detail ?? {};
      if (code) this.addEntry(label ?? 'Operation', code);
    }) as EventListener);
  }

  /** Add a code snippet to the log. */
  addEntry(label: string, code: string): void {
    this.entries.push({ label, code, timestamp: new Date() });
    this.renderEntries();
    this.dispatchEvent(
      new CustomEvent('code-log-update', {
        detail: { count: this.entries.length },
        bubbles: true,
      }),
    );
  }

  /** Return the number of entries. */
  getCount(): number {
    return this.entries.length;
  }

  private render(): void {
    this.root.innerHTML = `
<style>
  :host { display: block; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; }

  .cl-header {
    display: flex; align-items: center; gap: 8px; margin-bottom: 10px;
  }
  .cl-actions { display: flex; gap: 6px; margin-left: auto; }
  .cl-btn {
    font-size: 11px; padding: 4px 10px; border: 1px solid #d2d2d7;
    border-radius: 4px; background: #fff; cursor: pointer;
  }
  .cl-btn:hover { background: #f0f4ff; }
  .cl-btn.primary { background: #0066cc; color: #fff; border-color: #0066cc; }
  .cl-btn.primary:hover { background: #0055b3; }
  .cl-btn.danger { color: #c00; }
  .cl-btn.danger:hover { background: #ffebee; }

  .cl-empty {
    text-align: center; padding: 24px 16px; color: #999; font-size: 12px;
    line-height: 1.6;
  }
  .cl-empty-icon { font-size: 28px; margin-bottom: 6px; }

  .cl-entries { display: flex; flex-direction: column; gap: 8px; }

  .cl-entry {
    border: 1px solid #d2d2d7; border-radius: 6px; overflow: hidden;
  }
  .cl-entry-header {
    display: flex; align-items: center; gap: 6px;
    padding: 6px 10px; background: #f5f6f8; cursor: pointer;
    font-size: 11px; font-weight: 600; color: #333;
    border-bottom: 1px solid #d2d2d7; user-select: none;
  }
  .cl-entry-header:hover { background: #eef0f4; }
  .cl-entry-header .cl-time {
    font-weight: 400; font-size: 10px; color: #999; margin-left: auto;
  }
  .cl-entry-header .cl-chevron {
    font-size: 10px; transition: transform .15s; color: #999;
  }
  .cl-entry.open .cl-chevron { transform: rotate(90deg); }
  .cl-entry-body {
    display: none; padding: 0; position: relative;
  }
  .cl-entry.open .cl-entry-body { display: block; }
  .cl-entry-body pre {
    margin: 0; padding: 10px 12px; font-size: 11px;
    font-family: 'SF Mono', Monaco, 'Cascadia Code', monospace;
    line-height: 1.5; white-space: pre-wrap; word-break: break-word;
    background: #fafbfc; color: #333; overflow-x: auto;
    max-height: 220px; overflow-y: auto;
  }
  .cl-copy-btn {
    position: absolute; top: 6px; right: 6px;
    font-size: 10px; padding: 2px 8px; border: 1px solid #d2d2d7;
    border-radius: 4px; background: #fff; cursor: pointer;
    opacity: 0; transition: opacity .15s;
  }
  .cl-entry-body:hover .cl-copy-btn { opacity: 1; }
  .cl-copy-btn:hover { background: #e8f5e9; }
</style>

<div class="cl-header">
  <div class="cl-actions">
    <button class="cl-btn primary" id="download-btn" title="Download all as .py">&#x2B07; Download .py</button>
    <button class="cl-btn danger" id="clear-btn" title="Clear log">&#x2715; Clear</button>
  </div>
</div>
<div id="entries">
  <div class="cl-empty">
    <div class="cl-empty-icon">&#x1F40D;</div>
    Python code for each API operation will appear here.<br/>
    Compose queries, run SPARQL, or resolve IRIs to get started.
  </div>
</div>
`;
    this.root.getElementById('download-btn')!.addEventListener('click', () => this.download());
    this.root.getElementById('clear-btn')!.addEventListener('click', () => this.clear());
  }

  private renderEntries(): void {
    const container = this.root.getElementById('entries')!;

    if (this.entries.length === 0) {
      container.innerHTML = '<div class="cl-empty">Python code for each API operation will appear here.<br/>Compose queries, run SPARQL, or resolve IRIs to get started.</div>';
      return;
    }

    container.innerHTML = '';
    const wrapper = document.createElement('div');
    wrapper.className = 'cl-entries';

    for (let i = this.entries.length - 1; i >= 0; i--) {
      const entry = this.entries[i];
      const div = document.createElement('div');
      div.className = 'cl-entry' + (i === this.entries.length - 1 ? ' open' : '');

      const time = entry.timestamp.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' });

      const header = document.createElement('div');
      header.className = 'cl-entry-header';
      header.innerHTML = '<span class="cl-chevron">&#x25B6;</span> ' + escapeHtml(entry.label) + ' <span class="cl-time">' + time + '</span>';
      header.addEventListener('click', () => div.classList.toggle('open'));

      const body = document.createElement('div');
      body.className = 'cl-entry-body';

      const pre = document.createElement('pre');
      pre.textContent = entry.code;

      const copyBtn = document.createElement('button');
      copyBtn.className = 'cl-copy-btn';
      copyBtn.textContent = '\u{1F4CB} Copy';
      copyBtn.addEventListener('click', (e) => {
        e.stopPropagation();
        navigator.clipboard.writeText(entry.code).then(() => {
          copyBtn.textContent = '\u2713 Copied';
          setTimeout(() => { copyBtn.textContent = '\u{1F4CB} Copy'; }, 1500);
        });
      });

      body.append(pre, copyBtn);
      div.append(header, body);
      wrapper.append(div);
    }

    container.append(wrapper);
    wrapper.firstElementChild?.scrollIntoView({ block: 'nearest' });
  }

  private download(): void {
    if (this.entries.length === 0) return;

    const header = [
      '"""',
      'rdfsolve session log',
      'Generated: ' + new Date().toISOString(),
      'Operations: ' + this.entries.length,
      '"""',
      '',
    ].join('\n');

    const blocks = this.entries.map((e, i) => {
      const sep = '# ' + '\u2500'.repeat(60);
      const time = e.timestamp.toISOString();
      return sep + '\n# [' + (i + 1) + '] ' + e.label + '  (' + time + ')\n' + sep + '\n\n' + e.code;
    });

    const content = header + blocks.join('\n\n\n') + '\n';
    const blob = new Blob([content], { type: 'text/x-python' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'rdfsolve_session_' + Date.now() + '.py';
    a.click();
    URL.revokeObjectURL(url);
  }

  private clear(): void {
    this.entries = [];
    this.renderEntries();
    this.dispatchEvent(
      new CustomEvent('code-log-update', {
        detail: { count: 0 },
        bubbles: true,
      }),
    );
  }
}

customElements.define('code-log', CodeLog);
